-- Cambridge IELTS 20 - Reading Data
-- Run AFTER cam20_01_structure.sql

-- Reading Passages (3 passages)
INSERT INTO `tb_reading_passages` (`passage_id`, `lesson_id`, `passage_title`, `passage_text`, `word_count`, `difficulty_level`, `topic_category`, `source`, `created_at`) VALUES
(2001, 2005, 'Urban Green Spaces and Public Health',
'Paragraph A: In recent decades, city planners have recognised that urban green spaces — parks, gardens, tree-lined streets and riverbanks — play a vital role in improving the physical and mental health of residents. Studies conducted in cities across Europe and North America consistently show that people living within 300 metres of a park report lower levels of stress, anxiety and cardiovascular disease.\n\nParagraph B: The mechanisms behind these benefits are both direct and indirect. Direct exposure to natural environments has been shown to reduce cortisol levels and lower blood pressure within as little as twenty minutes. Indirectly, parks encourage physical activity: walking, cycling and outdoor exercise that might not otherwise occur in dense urban settings.\n\nParagraph C: Despite the evidence, many rapidly growing cities face a shortage of accessible green space. Land values in central districts often make park creation financially unviable, and existing green areas are sometimes sold for commercial development. In response, some municipalities have adopted innovative approaches such as rooftop gardens, vertical forests on building facades, and converting disused railway lines into linear parks.\n\nParagraph D: Critics point out that the distribution of green space is frequently unequal. Wealthier neighbourhoods tend to have more and better-maintained parks, while lower-income areas may have only small, poorly equipped lots. Addressing this disparity requires targeted investment policies that prioritise underserved communities rather than allocating funds evenly across all districts.',
310, 'band_5_6', 'health and environment', 'Cambridge IELTS 20 style', NOW()),

(2002, 2006, 'Sleep, Memory and Academic Performance',
'Paragraph A: The relationship between sleep and cognitive function has been a subject of scientific inquiry for over a century. Modern neuroscience has confirmed what students have long suspected: adequate sleep is essential for consolidating new information into long-term memory. During deep sleep stages, the hippocampus replays patterns of neural activity recorded during the day, transferring them to the neocortex for permanent storage.\n\nParagraph B: Research at the University of Lübeck demonstrated that participants who slept for eight hours after learning a set of word pairs recalled 92 percent of them correctly the following day, compared with just 74 percent for a group that remained awake for the same period. Crucially, the sleeping group also showed superior performance on creative problem-solving tasks, suggesting that sleep enhances not only rote memory but also flexible thinking.\n\nParagraph C: Despite this evidence, surveys indicate that university students average only 6.2 hours of sleep per night — well below the recommended seven to nine hours. The consequences extend beyond memory: sleep deprivation impairs attention, decision-making and emotional regulation. A longitudinal study tracking 3,000 undergraduates found that each hour of sleep lost per night was associated with a 0.15 drop in cumulative grade point average over an academic year.\n\nParagraph D: Universities have begun to respond. Several institutions now schedule no examinations before 10 AM, and some offer workshops on sleep hygiene as part of orientation programmes. However, cultural attitudes that glorify late-night studying remain a significant barrier to change.',
280, 'band_6_7', 'education and science', 'Cambridge IELTS 20 style', NOW()),

(2003, 2007, 'Artificial Intelligence in Clinical Diagnostics',
'Paragraph A: The application of artificial intelligence to medical diagnostics represents one of the most promising and contentious developments in contemporary healthcare. Machine-learning algorithms trained on millions of labelled medical images can now identify certain conditions — including diabetic retinopathy, skin cancer and pneumonia — with accuracy comparable to, and occasionally exceeding, that of experienced specialists.\n\nParagraph B: A 2019 meta-analysis published in The Lancet Digital Health reviewed 82 studies comparing deep-learning systems with healthcare professionals. The pooled sensitivity of AI systems was 87 percent, matching the clinicians'' 86.4 percent. However, the specificity of AI was lower in several categories, meaning it produced more false positives — flagging healthy patients as potentially ill.\n\nParagraph C: Regulatory frameworks have struggled to keep pace with the technology. Traditional medical device approval assumes a fixed product, yet AI models may be updated continuously as new data becomes available. The US Food and Drug Administration introduced a pilot programme in 2021 allowing iterative updates under a predetermined change-control plan, but many jurisdictions still lack equivalent guidance.\n\nParagraph D: Ethical concerns centre on data bias and accountability. If a diagnostic algorithm is trained predominantly on images from one ethnic group, its accuracy may decline for others. Furthermore, when an AI system contributes to a misdiagnosis, assigning legal responsibility between the developer, the hospital and the supervising clinician remains unresolved in most legal systems.',
270, 'band_6_7', 'technology and medicine', 'Cambridge IELTS 20 style', NOW());

-- Reading Questions (5 per passage = 15 total)
INSERT INTO `tb_reading_questions` (`question_id`, `passage_id`, `question_type`, `question_number`, `question_text`, `correct_answer`, `options`, `explanation`, `band_target`, `paragraph_reference`, `created_at`) VALUES
-- Passage 1: Urban Green Spaces
(2001, 2001, 'true_false_not_given', 1, 'People living near parks have lower rates of heart disease.', 'True', '["True","False","Not Given"]', 'Paragraph A states lower cardiovascular disease.', 6.0, 'A', NOW()),
(2002, 2001, 'true_false_not_given', 2, 'Cortisol reduction requires at least one hour in nature.', 'False', '["True","False","Not Given"]', 'Paragraph B says within twenty minutes.', 6.0, 'B', NOW()),
(2003, 2001, 'sentence_completion', 3, 'Some cities have converted old railway lines into ____ parks.', 'linear', NULL, 'Paragraph C mentions linear parks.', 6.0, 'C', NOW()),
(2004, 2001, 'multiple_choice', 4, 'According to Paragraph D, green space distribution is:', 'B', '["A. improving steadily","B. frequently unequal","C. centrally managed","D. no longer a concern"]', 'Critics note unequal distribution.', 6.5, 'D', NOW()),
(2005, 2001, 'sentence_completion', 5, 'Investment policies should prioritise ____ communities.', 'underserved', NULL, 'Paragraph D states underserved communities.', 6.0, 'D', NOW()),
-- Passage 2: Sleep and Learning
(2006, 2002, 'true_false_not_given', 6, 'During deep sleep the hippocampus replays daytime neural activity.', 'True', '["True","False","Not Given"]', 'Stated directly in Paragraph A.', 6.5, 'A', NOW()),
(2007, 2002, 'sentence_completion', 7, 'The sleeping group recalled ____% of word pairs correctly.', '92', NULL, 'Paragraph B gives the figure.', 6.5, 'B', NOW()),
(2008, 2002, 'multiple_choice', 8, 'University students average ____ hours of sleep per night.', 'C', '["A. 5.8","B. 7.0","C. 6.2","D. 8.0"]', 'Paragraph C states 6.2 hours.', 6.5, 'C', NOW()),
(2009, 2002, 'sentence_completion', 9, 'Each lost hour of sleep was linked to a ____ GPA drop.', '0.15', NULL, 'Paragraph C gives 0.15 drop.', 6.5, 'C', NOW()),
(2010, 2002, 'true_false_not_given', 10, 'All universities now ban exams before 10 AM.', 'False', '["True","False","Not Given"]', 'Only several institutions, not all.', 6.5, 'D', NOW()),
-- Passage 3: AI in Healthcare
(2011, 2003, 'multiple_choice', 11, 'AI diagnostic accuracy compared to specialists is:', 'B', '["A. always higher","B. comparable overall","C. much lower","D. untested"]', 'Meta-analysis shows comparable pooled sensitivity.', 7.0, 'B', NOW()),
(2012, 2003, 'sentence_completion', 12, 'AI systems produced more false ____ than clinicians.', 'positives', NULL, 'Lower specificity means more false positives.', 7.0, 'B', NOW()),
(2013, 2003, 'true_false_not_given', 13, 'The FDA now allows continuous AI model updates under a change-control plan.', 'True', '["True","False","Not Given"]', 'Paragraph C describes the FDA pilot programme.', 7.0, 'C', NOW()),
(2014, 2003, 'sentence_completion', 14, 'Training bias may reduce accuracy for certain ____ groups.', 'ethnic', NULL, 'Paragraph D discusses ethnic group bias.', 7.0, 'D', NOW()),
(2015, 2003, 'multiple_choice', 15, 'Legal responsibility for AI misdiagnosis is:', 'D', '["A. always the developer","B. the hospital","C. the clinician","D. unresolved in most systems"]', 'Paragraph D says unresolved.', 7.0, 'D', NOW());
